#The name of the build
name: DataFlow - ETL
#Declaring the branches
on:
  push:
    branches:
      - 'dev'
  #Setting the time the build will be wunning everyday
  # schedule:
  #   - cron: '30 * * * *'
#Starting jobs and workflow
jobs:
  ETL:
    #Here we establishing the os as needed
    runs-on: ubuntu-22.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    #Setting up python version and action setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.7'
    #Installing all needed dependencies
    - name: Installing Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    #Running ETL Flow Process
    - name: Running ETL Flow 
      run: |
        cd code/ && python sakani_etl.py
        echo "Done the process of the ETL!"
      shell: sh

    #Commiting files after updating the dataset
    - name: Commit New Changes
      run: |
        git config --local user.email "zaak0101@hotmail.com"
        git config --local user.name "Abdulrazak A. Othman"
        git add -A
        git commit -m "Done Updating (Dataset and DB)" -a --allow-empty
    #Pushing changes
    - name: Push New Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
