#The name of the build
name: SonarCloud - QA Testing
#Declaring the branches and types
on:
  push:
    branches:
      - 'main'
  #Setting the time the test will be running everyday
  schedule:
    - cron: '55 * * * *'
#Starting jobs and workflow
jobs:
  SonarCloud:
    name: SonarCloud
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan - Analyzing the Code
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}55